version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: avara_monolith
    environment:
      POSTGRES_USER: av_monolith
      POSTGRES_PASSWORD: av_monolith
      POSTGRES_DB: av_monolith
    ports:
      - "5444:5432"
    volumes:
      - av_data:/var/lib/postgresql/data

  channel_db:
    image: postgres:latest
    container_name: avara_channel
    environment:
      POSTGRES_USER: av_channel
      POSTGRES_PASSWORD: av_channel
      POSTGRES_DB: av_channel
    ports:
      - "5445:5432"
    volumes:
      - channel_data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

volumes:
  av_data: 
  redis_data: 
  channel_data: 